### ISSUE TITLE
Gif for stove

### ISSUE THREAD

**Issue by addison-grant** [addison-grant/sweat-equity-2#1]
Put the GIFs in the directory `src/img/Stove/conditions/`. (Please make the directory if it doesn't exist.)

**Comment by addison-grant** [comment]
Let me know if you need help. Helpful ImageMagick command:
```
convert -dispose previous <frame1.png> [<frame2.png> ...] -set delay 25 <output.gif>
```

**Comment by JasonIqbal** [comment]
I made the images. The command line wasn't working in windows and we agreed to convert it on your mac instead. Thank you

**Comment by JasonIqbal** [comment]
Thanks
