### ISSUE TITLE
website availability

### ISSUE THREAD

**Issue by JasonIqbal** [addison-grant/sweat-equity-2#16]
The website http://sweat-equity.xyz typically hangs on first load, but works on second load. Is the webpage host spinning up an instance of it on first request? I could manually put a version of the game on my amazon website with permission of the group.

**Comment by addison-grant** [comment]
I'm okay with that. I defer to @sterlinghirsh.

**Comment by sterlinghirsh** [comment]
Yep you got it right @JasonIqbal that's exactly it. I'm using heroku free tier. I can pay $7 a month to heroku and they can stop spinning down our instance every chance they get, but first let's have you try installing it. If we like the performance and ease of updates we can transition the domain to it if you want. Good looking out! Most people I show comment on it and I just haven't wanted to pay the money.

**Comment by JasonIqbal** [comment]
Okay I'll work on it and comment back when I have it up and running.

**Comment by JasonIqbal** [comment]
http://jasoniqbal.com/sweat-equity/index.html
